"""Weights & Biases logging that cannot take the run down with it.

Tracking is a submission requirement, which makes it tempting to call the
library directly. That couples every experiment to a network service: a
missing API key, an expired token or an outage then kills a four-hour training
run at the logging call rather than at the start, and the work is gone.

So every call goes through here, and the contract is:

* **No key configured -> offline mode, automatically.** Runs are written to
  ``wandb/`` and can be uploaded later with ``wandb sync``. Nothing is lost
  and nothing blocks.
* **Library missing or erroring -> a no-op recorder.** The run continues and
  metrics still land in ``outputs/metrics.jsonl``, which is the copy the
  report is actually built from.

That last point is the important one: the JSONL is the source of truth and
wandb is a mirror of it, not the other way round. A results table that can
only be regenerated by querying a web service is not reproducible.
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

__all__ = ["Run", "init", "git_provenance"]

_LOCAL = Path("outputs/metrics.jsonl")


def git_provenance() -> dict[str, Any]:
    """``{"git": "<sha>", "git_dirty": bool}``, best-effort and never fatal.

    Every recorded metric should be traceable to the code that produced it.
    Without this the 60+ measured numbers in SESSION-KNOWLEDGE cannot be tied
    to a revision, which is the difference between a result and an anecdote.

    **The dirty flag is the part that matters.** A bare SHA recorded from a
    modified working tree is worse than no SHA: it names a revision that did
    not produce the number. MLflow records the commit and has no dirty flag;
    W&B captures a diff but only when code saving is enabled, and it is off
    here. So neither tool would give us this and we record it ourselves.

    Subprocess failures (no git, not a repo, git missing from PATH) degrade to
    ``{"git": None}`` rather than raising -- logging must never be able to
    take down a four-hour fit, which is the whole premise of this module.
    """
    import subprocess                                      # noqa: PLC0415
    try:
        root = Path(__file__).resolve().parents[2]
        def _g(*args: str) -> str:
            return subprocess.run(["git", *args], cwd=root, capture_output=True,
                                  text=True, timeout=5, check=True).stdout.strip()
        return {"git": _g("rev-parse", "HEAD")[:12],
                "git_dirty": bool(_g("status", "--porcelain"))}
    except Exception:
        return {"git": None, "git_dirty": None}


_GIT = git_provenance()


class Run:
    """Thin wrapper. ``run.log(...)`` always writes locally, wandb if it can."""

    def __init__(self, name: str, config: dict[str, Any], backend: Any = None,
                 local: Path = _LOCAL) -> None:
        self.name, self.config, self._wb = name, config, backend
        self._local = local
        self._local.parent.mkdir(parents=True, exist_ok=True)
        self._emit({"event": "init", "config": config})

    @property
    def offline(self) -> bool:
        return self._wb is None

    def _emit(self, payload: dict[str, Any]) -> None:
        rec = {"run": self.name,
               "t": datetime.now(timezone.utc).isoformat(timespec="seconds"),
               # Resolved once at import, not per call: `git status` on a repo
               # this size costs ~50ms, and _emit runs every logged step.
               **_GIT,
               **payload}
        with self._local.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(rec, default=str) + "\n")

    def log(self, metrics: dict[str, Any], step: int | None = None) -> None:
        self._emit({"step": step, **metrics})
        if self._wb is not None:
            try:
                self._wb.log(metrics, step=step)
            except Exception as exc:                      # never fatal
                self._emit({"event": "wandb_log_failed", "error": repr(exc)})
                self._wb = None

    def summary(self, **kv: Any) -> None:
        self._emit({"event": "summary", **kv})
        if self._wb is not None:
            try:
                self._wb.summary.update(kv)
            except Exception:
                pass

    def finish(self) -> None:
        self._emit({"event": "finish"})
        if self._wb is not None:
            try:
                self._wb.finish()
            except Exception:
                pass


def _has_netrc() -> bool:
    """Whether `wandb login` has left a credential file behind.

    Checking only ``~/.netrc`` was wrong on Windows, where wandb writes
    ``~/_netrc``: a logged-in machine was forced into offline mode, and every
    run landed in ``wandb/offline-run-*`` with no URL. wandb itself reads
    ``$NETRC``, then ``~/.netrc``, then ``~/_netrc``.
    """
    cands = [os.environ.get("NETRC", ""),
             Path.home() / ".netrc", Path.home() / "_netrc"]
    return any(c and Path(c).exists() for c in cands)


def init(name: str, config: dict[str, Any] | None = None,
         project: str = "m31-patient-timeline") -> Run:
    """Local recorder always; the wandb backend only when asked for.

    **Opt-in, and the reason is a lost run.** Even in offline mode wandb
    spawns a background service process, and with several runs in flight that
    service died and took a 40-minute gradient-boosting fit down with it --
    ``ConnectionAbortedError`` raised from wandb's own teardown, *after* the
    work was done and outside any call this module wraps. A wrapper cannot
    catch an exception thrown by someone else's atexit handler, so the only
    reliable fix is not to start the service unless it is wanted.

    Set ``WANDB=1`` (or ``WANDB_API_KEY``) to enable it. Everything is written
    to ``outputs/metrics.jsonl`` either way, and that file, not the dashboard,
    is what the report is built from.
    """
    config = config or {}
    want = (os.environ.get("WANDB", "").lower() in {"1", "true", "yes"}
            or bool(os.environ.get("WANDB_API_KEY")))
    backend = None
    if want:
        try:
            import wandb                                   # noqa: PLC0415
            if not (os.environ.get("WANDB_API_KEY") or _has_netrc()):
                os.environ.setdefault("WANDB_MODE", "offline")
            backend = wandb.init(project=project, name=name, config=config,
                                 reinit=True)
        except Exception:
            backend = None
    return Run(name, config, backend)
